version: '3.8'

services:
  mariadb:
    build: .
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    shm_size: '256mb'
